DB_HOST     = "ep-spring-band-anrkztoc.c-6.us-east-1.aws.neon.tech"
DB_PORT     = "5432"
DB_NAME     = "neondb"
DB_USER     = "neondb_owner"
DB_PASSWORD = "npg_N8KgiFSIJ9Ay"
GEMINI_API_KEY = "AIzaSyBviIG7ayaS16jwbkhIFhI1zDRrzPsE-4o"