DB_HOST = "caboose.proxy.rlwy.net"
DB_PORT = "15313"
DB_NAME = "railway"
DB_USER = "postgres"
DB_PASSWORD = "HOqFAbtcTUClCKnlzwVylSewcymyqPuH"
GEMINI_API_KEY = "AIzaSyBviIG7ayaS16jwbkhIFhI1zDRrzPsE-4o"