DB_HOST = "caboose.proxy.rlwy.net"
DB_PORT = "15313"
DB_NAME = "railway"
DB_USER = "postgres"
DB_PASSWORD = "HOqFAbtcTUClCKnlzwVylSewcymyqPuH"
GEMINI_API_KEY = "AIzaSyCEWS13Zip2uoHKHvySUAAiGcXS1mxo_e4"